### ISSUE TITLE
Support multiple tsconfig.json files per workspace

### ISSUE THREAD

**Issue by GaurangTandon** [danvk/any-xray#10]
I installed the extension and get this error: `No tsconfig.json found in the workspace folder`
I have a monorepo, and the directory structure contains jsconfig.json files in varied places, like so:

```text
workspace root
  - package1
    - jsconfig.json
  - package2
    - src
      - jsconfig.json
  - package3
    - jsconfig.json
  ...
```

Would be great to support this setup. Thanks! 🙂

**Comment by danvk** [comment]
I just published 0.2.0, which should fix this and many other configuration issues. If it doesn't, please re-open the issue and point me at the project source.
