### ISSUE TITLE
Not working in bun repo

### ISSUE THREAD

**Issue by danvk** [danvk/any-xray#11]
https://github.com/deanylev/any-xray-not-working

cc @deanylev

**Comment by danvk** [comment]
The issue is that any-xray is looking under `node_modules/typescript` for lib files. So one immediate fix is to install TypeScript itself as a dev dependency:

    npm install -D typescript

Is that not a thing one typically does with Bun?

<img width="868" alt="image" src="https://github.com/user-attachments/assets/9c50160b-e9cd-42a7-8530-0288a14d39ea">

**Comment by deanylev** [comment]
Seems like pebkac on my behalf, if I `bun init` a fresh project I get `typescript` as a peer dependency. Must've set up this one up manually. Thanks!

**Comment by danvk** [comment]
Thanks for checking. You were probably getting VS Code's copy of TypeScript before. There's going to be a long tail of configuration issues until I implement something like #14.
