### ISSUE TITLE
Can't install in Cursor

### ISSUE THREAD

**Issue by samdeanpinknews** [danvk/any-xray#12]
Hey.

You might not care as you're targeting Visual Sstudio, but I get an error message trying to install this in Cursor.

`Can't install 'danvk.any-xray' extension because it is not compatible with the current version of Cursor (version 0.41.2, VSCode version 1.91.1).`

I confess I don't have any suggestion how to fix this, aside from 'Just use Visual Studio' :)

Thanks.

**Comment by danvk** [comment]
Try installing 0.1.1? I lowered the required version to support Cursor: https://github.com/danvk/any-xray/blob/main/CHANGELOG.md#011

**Comment by samdeanpinknews** [comment]
Oh, ha, I've just make a pull request whoch (hopefully) fixes this another way!

**Comment by danvk** [comment]
Seems to be working the lower version requirements in 0.1.1, so I'm going to close this out.
