### ISSUE TITLE
Piggyback on VS Code's TypeScript Language Service

### ISSUE THREAD

**Issue by danvk** [danvk/any-xray#14]
Ashley Claymore [pointed me](https://twitter.com/acutmore/status/1840654332032606234) to Orta's twoslash extension, which [gets quickinfo](https://github.com/orta/vscode-twoslash-queries/blob/4a564ada9543517ea8419896637c737229109ac5/src/helpers.ts#L7-L18) directly from the same TypeScript language service as VS Code:

```ts
/** Leverages the `tsserver` protocol to try to get the type info at the given `position`. */
export async function quickInfoRequest(model: Model, position: vscode.Position) {
  const { scheme, fsPath, authority, path } = model.uri;
  return await vscode.commands.executeCommand<QuickInfoResponse | undefined>(
    "typescript.tsserverRequest",
    "quickinfo",
    {
      file: scheme === 'file' ? fsPath : `^/${scheme}/${authority || 'ts-nul-authority'}/${path.replace(/^\//, '')}`,
      line: position.line + 1,
      offset: position.character,
    } satisfies FileLocationRequestArgs
  );
}
```

The same approach _should_ work for this extension as well. The approach would be:

- Parse the TS document (should be much less sensitive to project configuration)
- Do a traversal to find the identifiers in the visible range of the editor
- Get quickinfo for all of these

This should reduce overhead (by re-using the same language service as VS Code) and reduce the possibility of configuration mismatches (like #1 and #11).

**Comment by hediet** [comment]
I love the idea of this extension! 

Having a typescript language service plugin would make performance much better, then you don't even need to do the parsing or calling quickinfo repeatedly. It is also much more robust.

This is how I did it for a different type-driven VS Code extension: 
* [Define an API for VS Code <-> TS Language Server communication](https://github.com/microsoft/vscode-ts-file-path-support/blob/e29c85be64cac86e343e352d584995b34048d94e/language-service-plugin/src/api.ts#L3)
* [Implement and expose the API in a language server plugin](https://github.com/microsoft/vscode-ts-file-path-support/blob/e29c85be64cac86e343e352d584995b34048d94e/language-service-plugin/src/index.ts#L8)
* [Create a client for the API from the extension](https://github.com/microsoft/vscode-ts-file-path-support/blob/e29c85be64cac86e343e352d584995b34048d94e/vscode-extension/src/index.ts#L9)
* [Declare the plugin as typescript server plugin contribution in the VS Code extension package.json](https://github.com/microsoft/vscode-ts-file-path-support/blob/e29c85be64cac86e343e352d584995b34048d94e/vscode-extension/package.json#L44)
* [Have tests that use the API](https://github.com/microsoft/vscode-ts-file-path-support/blob/e29c85be64cac86e343e352d584995b34048d94e/language-service-plugin/test/tests.test.ts#L26)


At the moment, `createTsLspCustomServiceClient` uses a very hacky implementation, but if https://github.com/microsoft/vscode/issues/218275 lands, it would be much easier.

**Comment by danvk** [comment]
Thanks for the pointers, @hediet. I'd seen that the type-coverage extension achieves something similar to any-xray by [defining a language service plugin](https://github.com/plantain-00/type-coverage/blob/906bc5b784ccaafac988d392aa21fdf8c6786ba9/packages/plugin/src/index.ts). I dismissed that approach because I thought it could only generate new diagnostics, whereas I just wanted to highlight the `any`s. I hadn't realized it's possible to define new commands.

So is your suggestion to add a "find the `any`s" command to the language service?
